### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by eliksr** [rsummers11/CADLab#1]
Hey,

I read the CVPR 2016 paper and I tried to read the main.ipynb to understand how to run this library..
Yet, I didn't figure out how to to run the whole project, because I didn't see command for RNN training and other files.

My question is, do you have a better comprehensive main file to understand the whole flow?
Thanks

**Comment by khcs** [comment]
Training and sampling RNN are rather straightforward in [txtrnn/train.lua](https://github.com/khcs/learning-to-read/blob/master/txtrnn/train.lua) and [txtrnn/sample.lua](https://github.com/khcs/learning-to-read/blob/master/txtrnn/sample.lua).
Please pay attention to the options in the codes for the location of input files, pre-trained CNN models, etc.

**Comment by eliksr** [comment]
Ok, but in the paper the first RNN stage initialized with the CNN output, both in the training and sampling.

Did you implemented it in txtrnn/train.lua?

**Comment by khcs** [comment]
Yes, the same code is used for both stages.

**Comment by eliksr** [comment]
I have another question..
What package is "require 'file'" in train.lua?

**Comment by khcs** [comment]
https://github.com/torch/torch7/blob/master/doc/file.md

**Comment by eliksr** [comment]
Many thanks!
