### ISSUE TITLE
I got a MXNetError(py_str(_LIB.MXGetLastError()))

### ISSUE THREAD

**Issue by CedarYang** [rsummers11/CADLab#11]
INFO:root:providing maximum shape [('data', (2, 3, 512, 512)), ('gt_boxes', (2, 5, 5))] [('label', (2, 61440)), ('bbox_target', (2, 60, 64, 64)), ('bbox_weight', (2, 60, 64, 64))]
Error in proposal.infer_shape: Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\MXnet\lib\site-packages\mxnet\operator.py", line 751, in infer_shape_entry
    array('I', rshape[i])),
TypeError: array item must be integer

infer_shape error. Arguments:
  data: (2, 3, 288, 349)
  im_info: (2, 3)
  gt_boxes: (2, 1, 5)
  label: (2, 23220)
  bbox_target: (2, 60, 36, 43)
  bbox_weight: (2, 60, 36, 43)

I encountered these problems，but i am not  proficient in MXnet.i use MXnet1.2.1,
It doesn't look like a version problem.I sincerely hope that I can get your help about this iss.

**Comment by viggin** [comment]
I am not sure what is the problem. Can you step into the code to check which array caused the error?

**Comment by CedarYang** [comment]
i find the error is caused by the cudnn,because i used RTX2080TI,so the CUDA is 10.0,but the mxnet do not suproot this.so  how can i ues cpu run this code?
