### ISSUE TITLE
Data confusion

### ISSUE THREAD

**Issue by zhouhao-learning** [rsummers11/CADLab#14]
I really can't understand the data you provided, I see every patient.
Index_study index_series index" There are many images under the folder, but in the DL_info.csv file, not every image is included, so a fixed "patient"
Index_study index_series index" Isn't there just one image below the folder? Why are there many images, but only one?

Please give me some guidance, thank you

**Comment by viggin** [comment]
CT images are 3D volumes, while each png file in the folder is a 2D slice. In DL_info.csv, each line is a lesion bbox annotated by a radiologist on a 2D slice. However, in the image folders, we not only provide the 2D slice that contains the bbox, but also its 3D contexts, namely the slices below and above it. Please refer to our paper “DeepLesion: Automated Mining of Large-Scale Lesion Annotations and Universal Lesion Detection with Deep Learning” for details about the dataset. Thanks.
