### ISSUE TITLE
IoBB results

### ISSUE THREAD

**Issue by liveway6** [rsummers11/CADLab#15]
Hi, I sew the intersection over the detected bounding-box area ratio (IoBB) using in the paper 3DCE, but I can't found in the released code. And, I only found the Sensitivity (%) at 4 FPs per image of different methods when the IoBB was used as the overlap computation criterion (Table 2) . I'm full of curiosity in Sensitivity (%) at various FPs per image when the IoBB was used as the overlap computation criterion. Could you show me this results? 

Looking forward to your reply, Thanks!

**Comment by viggin** [comment]
Hi @liveway6 , I think you can get the IoBB-related results easily by modifying the function IOU in evaluation.py. Thanks.
