### ISSUE TITLE
what is the version of torchvision in LesaNet?

### ISSUE THREAD

**Issue by lucky-ing** [rsummers11/CADLab#17]
Hello, can you tell me the version of torchvision of your project? As you mention that the version of pytorch is 0.4.1.

**Comment by viggin** [comment]
Possibly 0.2.1, but newer versions should also work after some modification of the code.

**Comment by lucky-ing** [comment]
> Possibly 0.2.1, but newer versions should also work after some modification of the code.

thank you a lots. 0.2.1 is right, and the latest  version doesn't work.
