### ISSUE TITLE
How to get the word labels of correspond Patient_ID in DeepLesion Dataset

### ISSUE THREAD

**Issue by wangqin4377** [rsummers11/CADLab#18]
Hi,
I notice that the id column in /program_data/text_mined_labels_171_and_split.json are not same as the Patient_ID of the image in DeepLesion dataset.
So how to find a connection between two IDs or how to get the word labels of correspond patient image?
Besides, can u public the original diagnosis report data ?

Thanks,

**Comment by viggin** [comment]
The ID in text_mined_labels_171_and_split.json corresponds to the row number in DL_info.csv, starting from 0.
The original reports are currently unavailable.
