### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by eliksr** [rsummers11/CADLab#2]
Hey, 
I tried to run "train.lua" in txtrnn, but it failed with 'out of memory':
"cuda runtime error (2) : out of memory"

I have mac pro with NVIDIA GeForce GT 750M 2048MB

It failed when the program try to load the cnn model at line:230
```
 local immodel = torch.load(opt.immodelloc)
```

Can you give any advise to solve this issue?

Many Thanks

**Comment by khcs** [comment]
You have too little GPU memory.
The code was tested on NVIDIA Tesla K40 GPUs with 12GB memory.

**Comment by eliksr** [comment]
OK, now it make sense..
First, thanks a lot for this help,
Can you say what is the minimum GPU's memory to run this project?

**Comment by khcs** [comment]
You might be able to run it on your MacBook Pro by reducing the number of parameters but with compromised performance.
Or, you could run it on CPU but with compromised speed.

**Comment by eliksr** [comment]
Excellent! I'll try them both. 

Many thanks for you!
