### ISSUE TITLE
How can I get the JSRT mask?

### ISSUE THREAD

**Issue by LLLJJJYYY** [rsummers11/CADLab#21]
Hello.
I recently wanted to reproduce your research, but I have encountered difficulties in datasets. Can you share with me the JSRT and Montgomery data sets you have processed? If it is not convenient, can you tell me how can I get the JSRT mask?
Thank you.

**Comment by LLLJJJYYY** [comment]
PS: About Lung_Segmentation_XLSor.

**Comment by rafaelvalle** [comment]
https://www.isi.uu.nl/Research/Databases/SCR/download.php
