### ISSUE TITLE
[3DCE] Sensitivity of Different Lesion Sizes

### ISSUE THREAD

**Issue by xiecon** [rsummers11/CADLab#31]
I saw the results of sensitivity at 4 FPs of three lesion diameters (Table 1 and Table 4) provided in the paper 3DCE. But I can’t find the treatment for specific diameter range (e.g. <10 mm)  in the released code. I am confusing about how to calculate it.
Do you first select GT lesions bounding box that meets the diameter range and then compare them with all predicted bounding boxes? Or do you have any special treatments for the predict bounding boxes, such as not calculating bounding box beyond the certain range into false positive?

**Comment by viggin** [comment]
I first selected GT lesions bounding box that meets the diameter range and then compared them with all predicted bounding boxes to compute FROC curve. For the other two criteria (type and slice interval), I did the same.

**Comment by xiecon** [comment]
Thank you very much!
