### ISSUE TITLE
How to use the trained model?

### ISSUE THREAD

**Issue by lixingze** [rsummers11/CADLab#4]
I am impressed by your work, but i get some problems when i use the trained model.
No matter what the input is, i get the same output.

I also want to train the model myself, but it stop , and i have no idea.
```
==> online epoch # 1 [batchSize = 50]	
 [==================== 2461/2461 ==============>]  Tot: 37m43s | Step: 749ms    
Train accuracy: 0.00 %	 time: 2263.43 s	
==> testing	
Test accuracy:	47.070707070707	
==> online epoch # 2 [batchSize = 50]	
Killed................ 101/2461 ................]  ETA: 2h9m | Step: 3s289ms
```
Can you give me some advice?
Roger

**Comment by meijie0401** [comment]
@lixingze According to default.yml, groundtruth_file: 'DL_info.csv', I think you need to generate scv file for your dataset

**Comment by viggin** [comment]
I cannot comment based on the limited information. @lixingze Are you sure this is our program? Because the format of the output seems unlikely.

**Comment by hangingter** [comment]
@viggin I try to test the model by tools/test.py,  but I also get some problems, could you please give me some advices?
The output is as follows：
> 
INFO:root:Testing ...
INFO:root:DeepLesion_test num_images 4831
INFO:root:DeepLesion_test gt roidb loaded from cache/DeepLesion_test_gt_roidb.pkl
INFO:root:noisy boxes filtered, images: 4831 -> 4817, bboxes: 4927 -> 4912
file reading error: 000001_01_01/109.png

Maybe I didn't set the " default.yml"  correctly. And I also haven't found the trained model file yet.

**Comment by viggin** [comment]
@hangingter Please set "dataset_path" and "image_path" in default.yml to your paths.
The trained model should be saved in a folder "model". You can search "default.e2e_prefix" in the project. Note that the "/" should be changed to "\" if you are using Windows.

**Comment by hangingter** [comment]
Thank you!  I have completed the setup of "dataset_path" and "image_path", but I did not find the folder named "model" in this project, could you please add this file or send me the model? 
Non-commercial use.
This is my email: CJW@cug.edu.cn

**Comment by viggin** [comment]
@hangingter It's not hard to train one using our codes and data. Thanks!
