### ISSUE TITLE
[lesion_detector_3DCE] missing files

### ISSUE THREAD

**Issue by zydou** [rsummers11/CADLab#5]
When running the project [lesion_detector_3DCE], it raises many errors like:
```
import _init_paths
ImportError: No module named _init_paths

from rcnn.utils.timer import Timer
ImportError: No module named utils.timer

from rcnn.utils.load_data import load_gt_roidb, merge_roidb, filter_roidb
ImportError: No module named utils.load_data
```

https://github.com/rsummers11/CADLab/blob/ef7c4b7c4b6d106e285dd96518f7260c3288dd85/lesion_detector_3DCE/rcnn/tools/train.py#L4

https://github.com/rsummers11/CADLab/blob/ef7c4b7c4b6d106e285dd96518f7260c3288dd85/lesion_detector_3DCE/rcnn/tools/train.py#L18-L19

There is no subfolder named "utils" in `lesion_detector_3DCE/rcnn/`
It seems that you forgot to release these files.

**Comment by viggin** [comment]
Thanks for the feedback. The missing files have been added.

**Comment by maggiezha** [comment]
I am trying to run test.sh or train.sh of lesion_detect_3DCE, and got a problem:
I upzip the DeepLesion dataset, so the data is at: /home/data/DeepLesion/Images_png/000001_01_01/, etc, 
and I modified default.yml to be:
dataset_path: '/home/data/DeepLesion/'   
image_path: '/home/data/DeepLesion/Images_png/'
Then after running test.sh, it says:
INFO:root:Loading images with 2 threads.
INFO:root:loading parameters from model/3DCE 1 image 3 slice-0000.params
[16:12:54] include/dmlc/logging.h:308: [16:12:54] src/io/local_filesys.cc:166: Check failed: allow_null  LocalFileSystem: fail to open "model/3DCE 1 image 3 slice-0000.params"
Also if I print out 'mask' after line 188 of load_ct_img.py, it shows:
array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]]))
Could you please help me understand what and where should I have for 'model/3DCE 1 image 3 slice-0000.params' and how could I load the dataset properly? Many thanks!
