### ISSUE TITLE
ImportError at from ..cython.cpu_nms import cpu_nms

### ISSUE THREAD

**Issue by sindhura97** [rsummers11/CADLab#6]
As I run train.sh, I get the following error: 
ImportError: .........cython/cpu_nms.so: undefined symbol: PyFPE_jbuf

Please look at the image, I could not copy paste text.
![image](https://user-images.githubusercontent.com/42525474/44315405-c0afe980-a3f1-11e8-9ca5-654ea514f126.png)

Could you please help me fix this?
Thanks.

**Comment by liveway6** [comment]
Hey, how did you solve the problem? Can you please share?

**Comment by sindhura97** [comment]
Did not solve it yet. I just posted this an hour ago, waiting for help.

**Comment by viggin** [comment]
Perhaps you need to recompile cython modules. Try "python rcnn/cython/setup.py"

**Comment by sindhura97** [comment]
That worked! Thanks!
