### ISSUE TITLE
Question About DeepLesion Dataset

### ISSUE THREAD

**Issue by pqpq17** [rsummers11/CADLab#60]
I have a question regarding the dataset used for LesaNet. In the GitHub project (https://github.com/rsummers11/CADLab/tree/master/LesaNet), it is mentioned that the train/val/test_lesion_idxs are the lesion indices based on the DL_info.csv file. However, I could not find the corresponding 'lesion indices' column within the DL_info.csv file, while I only found 'Key_slice_index' column, which has left me a bit confused.

I would greatly appreciate any clarification you could provide regarding this matter. Thank you very much for your time, and I look forward to your response.

**Comment by viggin** [comment]
There should be a column named "train_val_test" in DL_info.csv

**Comment by pqpq17** [comment]
@viggin The DL_info.csv file does contain a "Train_Val_Test" column, but it only contains the values ​​1, 2, and 3, which are used to distinguish between the training, validation, and test sets.
The "text_mined_labels_171_and_split.json" file (in https://github.com/rsummers11/CADLab/tree/master/LesaNet) contains the labels of the lesion's body part, type, and attributes. These labels are mapped to "lesion_idxs", but "lesion_idxs" does not appear in the DL_info.csv file.

**Comment by viggin** [comment]
I'm sorry for the confusion. lesion_idxs is the row index in DL_info.csv

**Comment by pqpq17** [comment]
You really resolve my problem. Thank you! @viggin
